apiVersion: apps/v1beta1
kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    app: backend-service
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
    nodePort: 30002
  type: LoadBalancer