apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 7
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: backend:7c6218c
          ports:
            - name: http
              containerPort: 8080